name: clients
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  confetti: ^0.6.0
  flutter_credit_card: ^3.0.0
  lottie: ^2.6.0
  google_fonts: ^6.2.1
  supabase_flutter: ^2.8.3
  image_picker: ^0.8.4+4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
